[
  [
    "program-enter",
    "Program",
    "",
  ],
  [
    "callExpression-enter",
    "CallExpression",
    "Program",
  ],
  [
    "numberLiteral-enter",
    "NumberLiteral",
    "CallExpression",
  ],
  [
    "numberLiteral-exit",
    "NumberLiteral",
    "CallExpression",
  ],
  [
    "callExpression-enter",
    "CallExpression",
    "CallExpression",
  ],
  [
    "stringLiteral-enter",
    "StringLiteral",
    "CallExpression",
  ],
  [
    "stringLiteral-exit",
    "StringLiteral",
    "CallExpression",
  ],
  [
    "stringLiteral-enter",
    "StringLiteral",
    "CallExpression",
  ],
  [
    "stringLiteral-exit",
    "StringLiteral",
    "CallExpression",
  ],
  [
    "callExpression-exit",
    "CallExpression",
    "CallExpression",
  ],
  [
    "callExpression-exit",
    "CallExpression",
    "Program",
  ],
  [
    "program-exit",
    "Program",
    "",
  ],
]